### ISSUE TITLE
Doesn't support family-less instances

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-rpc#1]
An instance without a family throws a schema error, yet they are supported by the core library.

**Comment by tokejepsen** [comment]
Close?

**Comment by mottosso** [comment]
Feel free to close the things you think should close, and worst case I'll re-open. :)

**Comment by tokejepsen** [comment]
I'm not a collaborator for this repo:)

**Comment by mottosso** [comment]
Now you are. :)
